source("helpers.R")
source("uiHelpers.R")

#reset Shiny Server when data gets updated
# sgt <- c("All", t$tag)
# sgp <- c("All", p$tag)

build_ui <- function(){
  f <- fluidPage(
    shinyjs::useShinyjs(),
    tags$head(includeScript("google-analytics.js")),

    # titlePanel("UK Biobank S-PrediXcan association results"),
    # p("Data Release: October 16, 2017."),
    # p("These results are based on more than 2400 GWASes results generated by Neale Lab."),
    # p(strong("Recent increases in site traffic may cause slow performance."), style="color:red"),    
    # p(strong("We apologize for any inconvenience, and are working on a fix to be effected in the next few days."), style="color:red"),
    # p("We are working on identifying suspicious (false-positive) associations."),
    # p("GTEx Prediction models and covariances were built with GTEx V6P on HapMap SNPs."),
    # p("DGN Prediction model was built with Depression, Genes and Networks study data."),

    titlePanel("Metaxcan Association results (257 phenotypes)"),
    p("Data Release: September 26, 2017."),
    p("GTEx Prediction models and covariances built with GTEx V6P on HapMap SNPs."),
    p("DGN Prediction Model built data from the Depression Genes and Networks."),

    htmlTemplate("modal.html",
      title = "Phenotype Information",
      content = uiOutput("phenoInformation")
    ),
    h3("Results:"),
    fluidRow(column(2, selectInput( "display", "What to show:",
                 c(Results = 'results',
                 Phenotypes = 'pheno')))),
    conditionalPanel(
      condition = "input.display == 'results'",
      fluidRow(
        column(2, selectizeInput(inputId = "gene_name",
                                 label = "Filter by gene(s):",
                                 choices = NULL,
                                 selected = NULL,
                                 multiple = TRUE,
                                 # list of options for selectize.js available at: github.com/selectize/selectize.js/blob/master/docs/usage.md
                                 options = list(closeAfterSelect = FALSE, openOnFocus = TRUE, loadThrottle = NULL))),
        column(1),
        column(3, selectizeInput(inputId = "tissue",
                                label = "Filter by tissue(s):",
                                choices = NULL,
                                selected = NULL,
                                multiple = TRUE,
                                width = 500,
                                # list of options for selectize.js available at: github.com/selectize/selectize.js/blob/master/docs/usage.md
                                options = list(closeAfterSelect = FALSE, openOnFocus = TRUE, loadThrottle = NULL))),
        column(1),
        column(4, selectizeInput(inputId = "pheno",
                                 label = "Filter by phenotype(s):",
                                 choices = c('', p$tag),
                                 selected = '',
                                 multiple = TRUE,
                                 width = 650,
                                 # list of options for selectize.js available at: github.com/selectize/selectize.js/blob/master/docs/usage.md
                                 options = list(closeAfterSelect = FALSE, openOnFocus = TRUE, loadThrottle = NULL)))
      ),
      fluidRow(
        column(2, checkboxInput("ordered", label = "Order by p-value", value = TRUE)),
        column(1),
        column(1, numericInput("r2_threshold", "R2 threshold:", 0.01, min = 0, max = 1, step = 0.001)),
        column(1, numericInput("threshold", "P-value thres.:", 0.05, width = 200), min = 0, max = 1, step = 0.001),
        column(1, numericInput("limit", "Record limit:", 100), min = 1),
        column(1),
        column(1, checkboxInput("hide", label = "Hide suspicious results", value = TRUE)),
        column(1, checkboxInput("smr_f", label = "Only with SMR")),
        column(1, checkboxInput("twas_f", label = "Only with TWAS"))
      ),
      uiOutput("loading"),
      fluidRow(
        DT::dataTableOutput(outputId="results")
      ) #,
    ),
    conditionalPanel(
      condition = "input.display == 'pheno'",
      fluidRow(
        DT::dataTableOutput(outputId="pheno")
      )
    ),
    p("'Tissue' stands for different transcriptome models used when generating the association."),
    disclaimer(),
    cites()
  )
  f
}

shinyUI(
    build_ui()
)
