library(shiny)

appTitle <- "UK Biobank S-PrediXcan association results"
releaseDate <- "Data Release: October 16, 2017."

alertMessage <- ""
alertMessage <- "We are working on identifying suspicious (false-positive) associations."

dataInfo <- "These results are based on more than 2400 GWASes results generated by Neale Lab."
modelsInfo <- "GTEx Prediction models and covariances were built with GTEx V6P on HapMap SNPs.\nDGN Prediction model was built with the Depression, Genes and Networks study data."


header <- function(appTitle, releaseDate, dataInfo, modelsInfo, alertMessage){
    titlePanel(appTitle)
    p(releaseDate)
    p(dataInfo) # "the results are based on..."
    ifelse(alertMessage != "", p(alertMessage), {})
    p(modelsInfo)
}
